apiVersion: v1
kind: ReplicaSet
metadata:
  name: queue
  labels:
    app: custom-queue
    tier: queue
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      tier: queue
  template:
    metadata:
      labels:
        tier: queue
    spec:
      containers:
      - name: queue
        image: https://hub.docker.com/r/habuhaev96/custom_queue:latest
      - name: postgres
        image: https://hub.docker.com/_/postgres